<ul class="top-nav">
<li><a href="/ArtomiSys2/dashboard"<?php if ($this->active == 'index') : ?> class="active"<?php endif;?>>Hallintapaneeli</a></li>
<li><a href="/ArtomiSys2/dashboard/products"<?php if ($this->active == 'products') : ?> class="active"<?php endif;?>>Tuotteet</a></li>
<li><a href="/ArtomiSys2/dashboard/gallery"<?php if ($this->active == 'gallery') : ?> class="active"<?php endif;?>>Galleria</a></li>
<li><a href="/ArtomiSys2dashboard/settings"<?php if ($this->active == 'settings') : ?> class="active"<?php endif;?>>Asetukset</a></li>
</ul>