<a href="../dashboard/"<?php if ($this->active == 'index') : ?> class="active"<?php endif;?>>Home</a> | 
<a href="products"<?php if ($this->active == 'products') : ?> class="active"<?php endif;?>>Products</a> | 
<a href="gallery"<?php if ($this->active == 'gallery') : ?> class="active"<?php endif;?>>Gallery</a> | 
<a href="settings"<?php if ($this->active == 'settings') : ?> class="active"<?php endif;?>>Settings</a>