<!--<h1>ArtomiSys &mdash; Opas</h1>-->
<div style="text-align: center;">
	<img src="public/img/artomisys_header.png" style="height: 3em; margin: 12px;"/>
	<h1>Opas</h1>
</div>

<div class="block" style="float: right; width: 24%; box-sizing: border-box;">
	<h2>Sisällys</h2>
    <ul class="contents">
    	<li><a href="#top"><b>Yleistä</b></a></li>
    	<li><a href="#products"><b>Tuotteet</b></a>
    		<ul>
    			<li><a href="#create-new-product">Tuotteen lisääminen</a></li>
    			<li><a href="#edit-product">Tuotteen muokkaaminen</a></li>
    			<li><a href="#delete-product">Tuotteen poistaminen</a></li>
    		</ul>
    	</li>
    	<li><a href="#"><b>Galleria</b></a>
    		<ul>
    			<li><a href="#">Yleistä</a></li>
    			<li><a href="#">Yleistä</a></li>
    			<li><a href="#">Yleistä</a></li>
    		</ul>
    	</li>
    	<li><a href="#"><b>Asetukset</b></a></li>
    	<li><a href="/ArtomiSys2/dashboard/index/guide/info"><b>Tietoja ArtomiSys:sta</b></a></li>
    </ul>
</div>
<div class="block" style="float: left; width: 74%; box-sizing: border-box;">
	<span style="color: #C00; font-size: 110%;">
		<i>Opas on tulossa myöhemmin...</i>
	</span>

	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

	<h1 id="products">Tuotteet</h1>
	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

	<h2 id="create-new-product">Tuotteen lisääminen</h2>
	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

	<h2 id="edit-product">Tuotteen muokkaaminen</h2>
	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

	<h2 id="delete-product">Tuotteen poistaminen</h2>
	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

	<h1 id="settings">Asetukset</h1>
	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>
<p class="clear"></p>