<div class="wrapper">
	<div style="text-align: center;">
		<img src="<?=ROOT_DIR?>/img/artomisys_header.png" style="height: 3em; margin: 12px;"/>
	</div>

	<div class="block" style="text-align: center;">
		<h2>ArtomiSys 2 Sisällönhallintajärjestelmä</h2>
		<p>
			Copyright &copy; ArtomiSys Oy 2016<br/>
			Kehittäjä Miika Sikala<br/>
			Versio <strong><?=$this->version;?></strong>
			<p>Lähdekoodi: <a href="https://github.com/Spacha/ArtomiSys2" target="_blank">GitHub</a></p>
		</p>
	</div>
</div>