<span id="version"><?=$this->version;?></span>

<div id="login_header">
	<img src="<?=ROOT_DIR?>/img/artomisys_header.png"/>
</div>


<div id="login">
	<h1>Kirjaudu</h1>
	
	<form action="<?=ROOT_DIR?>/dashboard/login/login/true" method="post">
		<p><input type="text" name="username" placeholder="Käyttäjätunnus"></p>
		<p><input type="password" name="password" placeholder="Salasana"></p>

		<?php if(!empty($_SESSION['notification'])): ?>
		
		<!-- Show notification -->

		<div id="notification" class="inline-error">
			<?=$_SESSION['notification']['message']?>
			<?php $this->clearNotification()?>
		</div>

		<?php endif ?>

		<input type="submit" class="btn" style="font-size: 100%;" value="Kirjaudu">
	</form>
</div>
<div id="login_footer">
	&copy; Artomi Oy / <i>Miika Sikala</i>
</div>