<h1>Luo uusi tuote</h1>

<form action="/ArtomiSys2/dashboard/products/create/save" method="post" enctype="multipart/form-data">
	<p><b>Otsikko: </b></p>
	<p><input type="text" style="width: 100%; padding: 6px; font-size: 105%;" name="title"/></p>
	<p><b>Kuvaus: </b></p>
	<p><textarea name="content" style="width: 100%; height: 300px; padding: 6px; font-size: 105%;"></textarea></p>
	
	<p><a href="/ArtomiSys2/dashboard/products" class="btn" style="font-size: 100%;">Peruuta</a> <input type="submit" class="btn" style="font-size: 100%;" value="Valmis"/></p>
</form>