<h1 style="display: inline-block; width: 100%;">
	Luo uusi tuote
	<span class="hotbar"><a href="/ArtomiSys2/dashboard/index/guide#create-new-product" target="_blank" class="btn icon icon-help">Apua</a></span>
</h1>

<form action="/ArtomiSys2/dashboard/products/create/save" method="post" enctype="multipart/form-data">
	<p><b>Otsikko: </b></p>
	<p><input type="text" name="title"/></p>
	<p><b>Kuvaus: </b></p>
	<p><textarea name="content"></textarea></p>
	<p><b>Julkinen: </b><input type="checkbox" name="visible" value="1"/></p>
	
	<p>
		<input type="file" name="images[]" id="images" multiple/>
		<label for="images">Valitse kuvia</label>
	</p>

	<p><a href="/ArtomiSys2/dashboard/products" class="btn icon icon-back" style="font-size: 100%;">Peruuta</a> <input type="submit" class="btn" style="font-size: 100%;" value="Valmis"/></p>
</form>