<h1 style="display: inline-block; width: 100%;">
	Tuotteet <span class="header-count"><?=$this->productsCount;?></span>
	<span class="hotbar">
		<a href="/ArtomiSys2/dashboard/products/create" class="btn icon icon-plus">Lisää tuote</a>
		<a href="/ArtomiSys2/dashboard/index/guide#products" target="_blank" class="btn icon icon-help">Apua</a>
	</span>
</h1>

<?php if(count($this->products)): ?>

<table class="list">
	<tr><th>#</th><th>Tuotteen nimi</th><th>Luotu</th><th>Työkalut</th></tr>

<?php
foreach($this->products as $product) {
	echo "<tr>
		<td>{$product['id']}</td>
		<td><a href=\"/ArtomiSys2/dashboard/products/view/{$product['id']}\">{$product['title']}</a></td>
		<td>{$product['date']}</td>
		<td><a href=\"/ArtomiSys2/dashboard/products/edit/{$product['id']}\">Muokkaa</a> /
		<a href=\"/ArtomiSys2/dashboard/products/delete/{$product['id']}\">Poista</a></td>
		</tr>";
}
?>
<?php else: ?>

<div style="font-size: 130%; text-align: center; color: #666;">
	<span style="padding: 4px 16px; border: 1px solid #CCC;
				display: inline-block;
				border-radius: 1.2em;">
		<p>Ei tuotteita tällä hetkellä.</p>
	</span>
</div>

<?php endif; ?>

</table>