<h1 style="display: inline-block; width: 100%;">
<span style="font-size: 80%;"><?=$this->product['title'];?></span>
	<span class="hotbar">
		<a href="<?=ROOT_DIR?>/dashboard/products/edit/<?=$this->product['id'];?>" class="btn icon icon-edit">Muokkaa</a>
		<a href="<?=ROOT_DIR?>/dashboard/products/delete/<?=$this->product['id'];?>" class="btn icon icon-delete">Poista</a>
	</span>
</h1>

<?php if(isset($this->product['images']) && !empty($this->product['images'])): ?>

<div style="text-align: center;">
<?php

foreach($this->product['images'] as $img) {
	$img = ROOT_DIR .'/uploads/products/'. $img;
	echo '<img style="height: 160px; margin: 0 2px;" src="'.$img.'"/>';
}
?>
</div>

<?php endif; ?>

<table class="hor-list">
<tr>
<td><b>ID: </b></td>
<td><?=$this->product['id'];?></td></tr><tr>
<td><b>Julkinen: </b></td>
<td><?=($this->product['visible']) ? 'Kyllä' : 'Ei';?></td></tr>
<td><b>Katselukertoja: </b></td>
<td>ei saatavilla</td></tr>
</table>
<div class="block">

<p><strong>Kuvaus:</strong></p>
<?=nl2br($this->product['content']);?>

</div>

<a href="<?=ROOT_DIR?>/dashboard/products" class="btn icon icon-back" style="font-size: 100%;">Takaisin</a>
