<h1 style="display: inline-block; width: 100%;">
	Galleria <span class="header-count"></span>
	<span class="hotbar">
		<a href="/ArtomiSys2/dashboard/gallery/upload" class="btn icon icon-plus">Lisää kuvia</a>
		<a href="/ArtomiSys2/dashboard/index/guide#gallery" target="_blank" class="btn icon icon-help">Apua</a>
	</span>
</h1>

<div id="list-empty">
	<div>
		<img src="public/img/icons/info.png"/>
		<p>Ei kuvia tällä hetkellä.</p>
	</div>
</div>