<div class="wrapper">
	<h1 style="display: inline-block; width: 100%;">
		Galleria <span class="header-count"></span>
		<span class="hotbar">
			<a href="<?=ROOT_DIR?>/dashboard/gallery/upload" class="btn icon icon-plus">Lisää kuvia</a>
			<a href="<?=ROOT_DIR?>/dashboard/index/guide#gallery" target="_blank" class="btn icon icon-help">Apua</a>
		</span>
	</h1>

	<div id="list-empty">
		<div>
			<img src="<?=ROOT_DIR?>/img/icons/info.png"/>
			<p>Ei kuvia tällä hetkellä.</p>
		</div>
	</div>
</div>