<h1 style="display: inline-block; width: 100%;">
	Asetukset
	<span class="hotbar">
		<a href="/ArtomiSys2/dashboard/index/guide#settings" target="_blank" class="btn icon icon-help">Apua</a>
	</span>
</h1>

<div class="block">
	<p>
		<strong>Kirjautuneena: </strong><?=$this->userdata['name'];?>
		(id: <?=$this->userdata['id'];?>)
	</p>
</div>

<form action="/ArtomiSys2/dashboard/settings/changePassword" method="post">
	<div class="block">
		<table>
			<tr><h2>Vaihda salasana</h2></tr>
			<tr>
				<td>Vanha salasana: </td>
				<td><input type="password" name="oldPassword"/></td>
			</tr>
			<tr>
				<td>Uusi salasana: </td>
				<td><input type="password" name="newPassword"/></td>
			</tr>
			<tr>
				<td>Toista uusi salasana: </td>
				<td><input type="password" name="repeatNewPassword"/></td>
			</tr>
			<tr>
				<td></td>
				<td><input type="submit" value="Vaihda salasana" class="btn" style="font-size: 100%;"/></td>
			</tr>
		</table>
	</div>
</form>