<form action="/ArtomiSys2/test/index/true" method="post" enctype="multipart/form-data">
	<input type="file" name="images[]" multiple/>
	<input type="submit" value="Submit"/>
</form>


<?php

$allowed_exts = ['jpg','jpeg','png','gif'];
$uploads = scandir(PATH_ROOT.'/'.UPLOAD_DESTINATION);

foreach($uploads as $file) {
	if (in_array(pathinfo($file, PATHINFO_EXTENSION), $allowed_exts)) {
		echo '<li>'.$file.' <a href="/ArtomiSys2/test/deleteSingleImg/'.$file.'">Delete</a></li>';
	}
}

?>