<div class="wrapper">
    <h1>Ota yhteyttä</h1>
	
	<p>Kysy lisää palveluistamme, tarjonnastamme tai anna palautetta! Olemme palveluksessasi lähes vuorokauden ympäri, mutta paras aika on tavoitella arkipäivisin päiväsaikaan.</p>
	<p>Oheisesta kartasta näet hallin sijainnin.</p>
</div>
<div style="background: rgba(0,0,0,0.4); border-top: 1px solid #CCC;">
	<div class="wrapper clearfix">
		<div id="left-col">
			<h2>Yhteystiedot</h2>
			<table style="font-size: 120%;">
				<tr><td style="color: #FFF;"><b>Puh (Arto):&nbsp;&nbsp;&nbsp;&nbsp;</b></td><td>050 028 6549</td></tr>
				<tr><td style="color: #FFF;"><b>Sähköposti: </b></td><td><a href="mailto:posti@artomi.fi">if.imotra@itsop</a></td></tr>
				<tr><td style="color: #FFF;"><b>Postiosoite: </b></td><td>Halavatie 1, 86400 Vihanti</td></tr>
			</table>
		</div>
		<div id="right-col">
			<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d725.0637339789595!2d24.997504490014904!3d64.48560839181444!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4681009a4fd71bd5%3A0xd8d85ba730d53fde!2sKuljetus+Artomi+Oy!5e0!3m2!1sfi!2sfi!4v1473100287263" frameborder="0" style="border:0; width: 100%; height: 300px;" allowfullscreen></iframe>
		</div>
	</div>
</div>