<!DOCTYPE html>
<html>
	<head>
		<title>Kuljetus & Konepaja Artomi Oy</title>
		<meta charset="UTF-8"/>
		<meta name="viewport" content="width=device-width, initial-scale=1"/>
		
		<meta name="description" content="Kuljetus & konepaja Artomi Oy on Vihannissa toimiva kuljetusalan ja koneistuksen ammattilainen." />
		<meta name="keywords" content="Kuljetus Artomi Oy, metallityöt, koneistukset, Vihanti, kuorma-autokuljetukset, kuljetukset, konepaja" />
		
		<link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href="/css/main.css"/>
	</head>
	<body>
		<div id="top">
			<div class="wrapper">
				<div style="background: rgba(0,0,0,0.8); float: right; width: 200px; padding: 20px 60px; color: #EEE; border-right: 1px solid #CCC; border-left: 1px solid #CCC;">
					<h2 class="info">Artomi Oy</h2>
					<p>
						<b>Arto:</b> 050 028 6549
					</p>

					<p>Halavatie 1, 86400 VIHANTI</p>
				</div>
				<p style="clear: both;"></p>
			</div>
		</div>
		<div id="header">
			<div class="wrapper">
				<a href="#">
					<img src="img/logo.png" id="logo"/>
				</a>
				<ul id="nav">
					<li><a class="active" href="#">Etusivu</a></li>
					<li><a href="palvelut.html">Palvelut</a></li>
					<li><a href="tuotteet.html">Tuotteet</a></li>
					<li><a class="disabled">Galleria</a></li>
					<li><a href="yhteystiedot.html">Ota yhteyttä</a></li>
				</ul>
			</div>
		</div>
		<div class="wrapper">
			<div id="left-col">
				<div class="block">
					<h2>Tervetuloa Artomin nettisivuille!</h2>
					<p><span style="color: #FFF;"><b>Huomio!</b> Sivusto on vielä kehitysvaiheessa!</span></p>
					<p>Artomi Oy on vuonna 2008 perustettu vihantilainen huolto- ja konepajayritys. Toimipaikkana on edelleen Vihanti (Raahe) ja tarvittaessa sen lähialueet. Vihannin toimipisteessä on kattavasti varusteltu halli, jossa pääosa huoltotöistä tehdään. Myös myymälä ja toimisto löytyy hallin yhteydestä.</p>
					<p>Meiltä sujuu erittäin laajat metallityöt ja koneistukset sekä monipuoliset varaosapalvelut. Varaosien lisäksi myymme vaihtelevissa määrin kalustoamme, josta lisätietoja löydät <a href="">tuotteet</a>-osiosta.</p>
					<p>Hallillamme on laajat aukioloajat: arkipäivisin avaamme yleensä 7-8 aikaan, toisinaan aiemmin tai myöhemminkin. Halli on auki 16-17, toisinaan palvelemme jopa klo 24 asti.</p>
				</div>
			</div>
			<div id="right-col">
				<div style="background: #333; border: 1px solid #000; margin: 10px 0; color: #FFF; box-shadow: 2px 2px 8px rgba(0,0,0,0.2);">
					<div id="slideshow">
						<img src="img/Asfaltinajoa norjassa.jpg" style="width: 100%;">
					</div>
					<div style="padding: 10px;">Asfaltin ajoa Norjassa.</div>
				</div>
			</div>
			<p style="clear: both;"></p>
		</div>
		<div id="services">
			<div class="wrapper">
				 <div class="col">
					<img src="img/svc_koneistus.png"/>
					<h2>Koneistus</h2>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque sodales eu elit nec lacinia. Aenean sit amet erat pulvinar, placerat libero sed, tempor lectus. Nulla et lacus gravida, dignissim est quis, hendrerit lorem. Nullam posuere commodo placerat.</p>
					<a href="/palvelut.html#koneistus">Lue lisää &rsaquo;</a>
				</div>
				<div class="col">
					<img src="img/svc_huolto.png"/>
					<h2>Huolto</h2>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque sodales eu elit nec lacinia. Aenean sit amet erat pulvinar, placerat libero sed, tempor lectus. Nulla et lacus gravida, dignissim est quis, hendrerit lorem. Nullam posuere commodo placerat.</p>
					<a href="/palvelut.html#huolto">Lue lisää &rsaquo;</a>
				</div>
				<div class="col">
					<img src="img/svc_varaosat.png"/>
					<h2>Varaosat</h2>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque sodales eu elit nec lacinia. Aenean sit amet erat pulvinar, placerat libero sed, tempor lectus. Nulla et lacus gravida, dignissim est quis, hendrerit lorem. Nullam posuere commodo placerat.</p>
					<a href="/palvelut.html#varaosat">Lue lisää &rsaquo;</a>
				</div>
				<p style="clear: both;"></p>
			</div>
		</div>
		
		<div id="our-products">
			<div class="wrapper">
				<h1>Tutustu tuotteisiimme</h1>
				<p>Voit tutustua tarjontaamme tuotekatalogimme kautta, missä näet osan tuotteistamme. Suurin osa tuotteistamme on kuitenkin liikkeessämme.</p>
				<a href="tuotteet.html" id="goto-catalog">Tutustu tarjontaan &rsaquo;</a>
			</div>
		</div>
		
		<div id="footer">
			<div class="wrapper">
				&copy; Artomi Oy 2016
			</div>
		</div>
	</body>
</html>