<div class="wrapper">
	<div id="left-col">
		<div class="block">
			<h2>Tervetuloa Artomin nettisivuille!</h2>
			<p><span style="color: #FFF;"><b>Huomio!</b> Sivusto on vielä kehitysvaiheessa!</span></p>
			<p>Artomi Oy on vuonna 2008 perustettu vihantilainen huolto- ja konepajayritys. Toimipaikkana on edelleen Vihanti (Raahe) ja tarvittaessa sen lähialueet. Vihannin toimipisteessä on kattavasti varusteltu halli, jossa pääosa huoltotöistä tehdään. Myös myymälä ja toimisto löytyy hallin yhteydestä.</p>
			<p>Meiltä sujuu erittäin laajat metallityöt ja koneistukset sekä monipuoliset varaosapalvelut. Varaosien lisäksi myymme vaihtelevissa määrin kalustoamme, josta lisätietoja löydät <a href="<?=ROOT_DIR?>/tuotteet">tuotteet</a>-osiosta.</p>
			<p>Hallillamme on laajat aukioloajat: arkipäivisin avaamme yleensä 7-8 aikaan, toisinaan aiemmin tai myöhemminkin. Halli on auki 16-17, toisinaan palvelemme jopa klo 24 asti.</p>
		</div>
	</div>
	<div id="right-col">
		<div class="img-bordered fp-img">
			<img src="<?=ROOT_DIR?>/img/Asfaltinajoa norjassa.jpg">
			<div style="padding: 10px;">Asfaltin ajoa Norjassa.</div>
		</div>
	</div>
	<p style="clear: both;"></p>
</div>
<div id="services">
	<div class="wrapper">
		 <div class="col">
			<img src="<?=ROOT_DIR?>/img/svc_koneistus.png"/>
			<h2>Koneistus</h2>
			<p>Olipa kyse sitten pienestä viilauksesta tai monimutkaisemmasta metallihäkkyrästä, saamme metallin taipumaan monipuolisen laitteistomme ammattitaidon ansiosta.</p>
			<a href="<?=ROOT_DIR?>/services#koneistus">Lue lisää &rsaquo;</a>
		</div>
		<div class="col">
			<img src="<?=ROOT_DIR?>/img/svc_huolto.png"/>
			<h2>Huolto</h2>
			<p>Huollamme hyvin erilaisia laitteita koosta ja tyypistä riippumatta – ruohonleikkureista rekka-autoihin. Soita ja kysy lisää!</p>
			<a href="<?=ROOT_DIR?>/services#huolto">Lue lisää &rsaquo;</a>
		</div>
		<div class="col">
			<img src="<?=ROOT_DIR?>/img/svc_varaosat.png"/>
			<h2>Varaosat</h2>
			<p>Myymälästämme löytyy monipuolinen varaosavalikoima ja tarpeen mukaan kykenemme toimittamaan varaosia myös muualta nopealla aikataululla.</p>
			<a href="/services#varaosat">Lue lisää &rsaquo;</a>
		</div>
		<p style="clear: both;"></p>
	</div>
</div>

<div id="our-products">
	<div class="wrapper">
		<h1>Tutustu tuotteisiimme</h1>
		<p>Voit tutustua tarjontaamme tuotekatalogimme kautta, missä näet osan tuotteistamme. Suurin osa tuotteistamme on kuitenkin liikkeessämme.</p>
		<a href="<?=ROOT_DIR?>/tuotteet" id="goto-catalog">Tutustu tarjontaan &rsaquo;</a>
	</div>
</div>