<div class="content text-center">

	<div class="carousel">
		&nbsp;
	</div>

	<hr class="awesome">

	<h1>Monipuoliset metalli- ja konetyöt</h1>

	<p>Ammattitaitoista jälkeä metallin ja koneiden parissa pitkällä kokemuksella ja hyvällä näkemyksellä. Halliltamme löytyy monipuolinen ja nykyaikainen laitteisto huolto- sekä koneistustarpeisiin.</p>

	<div class="services">
	    <div class="col">
	    	<img src="img/services-engineering.png" class="head">
	    	<a><h4>KONEISTUS</h4></a>
	    	<p>Monipuolisen laitteiston ja osaamisen ansiosta meiltä hoituu monentyyppiset ja -kokoiset koneistustyöt..</p>
	    </div>
	    <div class="col">
	    	<img src="img/services-service.png" class="head">
	    	<a><h4>HUOLTO</h4></a>
	    	<p>Huollamme hyvin erilaisia laitteita koosta ja tyypistä riippumatta – ruohonleikkureista rekka-autoihin. Soita ja kysy lisää!</p>
	    </div>
	    <div class="col">
	    	<img src="img/services-parts.png" class="head">
	    	<a><h4>VARAOSAT</h4></a>
	      
	      	<p>Myymälästämme löytyy monipuolinen varaosavalikoima ja tarpeen mukaan kykenemme toimittamaan varaosia myös muualta nopealla aikataululla.</p>

	   	</div>
	   	<p class="clear"></p>
	</div>

	<!-- <div id="our-products">
		<div class="container">
			<h1>Tutustu tuotteisiimme</h1>
			<p>Voit tutustua tarjontaamme tuotekatalogimme kautta, missä näet osan tuotteistamme. Suurin osa tuotteistamme on kuitenkin liikkeessämme.</p>
			<a href="tuotteet.html" id="goto-catalog">Tutustu tarjontaan ›</a>
		</div>
	</div> -->
</div>
