<h1>Products</h1>

<p>Tuotekatalogissa esittelemme myytävissä olevaa kalustoamme. Voit tutustua tarjontaamme katalogin kautta ennen ostopäätöstä. Voit tutustua kalustoomme myös paikan päällä. Jos jokin tuote vaikuttaa kiinnostavalta, ota meihin yhteyttä sähköpostilla tai matkapuhelimella. Soittamalla asia yleensä hoituu nopeiten.</p>
<p>Huomaathan, että katalogissa on näkyvissä vain pieni osa tuotteistamme!</p>

<div id="products-list" class="text-center">

<?php
/* Preview images */
foreach ($this->products as $product) {
	echo "
		<a href='". ROOT_DIR ."/products/" . $product['id'] ."'>
			<div class='preview'>
				<span class='helper'></span>
				<div class='preview-img'>
					<img src='". $product['previewImg'] ."'>
				</div>
				<p><b>". $product['title'] ."</b></p>
			</div>
		</a>";
}
?>

</div>