<div class="wrapper">
	<div class="breadcrumb">
		<h1><a href="<?=ROOT_DIR.'/products/'?>">Tuotteet</a>
		<span class="break">&raquo;</span>
		<?=$this->product['title']?></h1>
	</div>

	<?php

	if(isset($this->product['images']) && !empty($this->product['images'])) {

		echo "<div class='product-imgs'>";
		
		foreach($this->product['images'] as $img) {
			$img = ROOT_DIR .'/uploads/products/'. $img;
			echo '<img src="'.$img.'"/>';
		}

		echo "</div>";
	}

	if (!empty($this->product['content'])) {
		$content = $this->product['content'];
	} else {
		$content = "Ei kuvausta";
	}
	
	?>
	
		<div style=''><h2> <?=$this->product['title']?> </h2>
			<span style='font-style: cursive; color: #EEE;'>
				<strong>Ilmoitus luotu:</strong> <?=$this->product['date']?>
			</span>
			<p> <?=nl2br($content)?> </p>
		</div>
		<div class="contact-banner">
			<!-- Kiinnostuitko!? Ota yhteyttä! -->
		</div>
	</div>
</div>