<div class="wrapper clearfix">
    <h1>Palvelumme</h1>
	
	<div id="left-col">
		
		<p>Tarjoamme monipuolisia palveluita mukaanlukien moninaiset metallistyöt, poraukset ja jyrsinnät. Lisäksi huollamme monentyyppistä ja -kokoista kalustoa vahvalla ammattitaidolla.</p>
		
		<h2 id="koneistus">Koneistus</h2>
		<p>Olipa kyse sitten pienestä viilauksesta tai monimutkaisemmasta metallihäkkyrästä, saamme metallin taipumaan monipuolisen laitteistomme ammattitaidon ansiosta.</p>
		
		<h2 id="huolto">Huolto</h2>
		<p>Huollamme hyvin erilaisia laitteita ruohonleikkureista rekka-autoihin.</p>
		
		<h2 id="varaosat">Varaosat</h2>
		<p>Meillä on laaja valikoima varaosia monenlaiseen käyttöön. Jos jotain osaa ei varastosta löydy, hankimme sellaisen puolestasi.</p>
		
		<h2 id="muut-palvelut">Muut palvelut</h2>
		
		<li>Koneistukset: Aarporaus, Sorvaukset, Jyrsintä, Poraus, Kiilaurat yms.
		<li>Metallityöt: Polttoleikkaus
		<li>Hydroscand Letkupalvelu
		<li>Hydr. Tiivisteet esim. Varren-, Männän-, Pyyhkijä- ja Akselitiivisteet
		<li>Hydraulisylinterit
		<li>Akut (Euroglobe, Bosch, Optima)
		<li>Pultit (8.8, 10.9 ja 12.9. tuumakoot, hienokierteiset ja kierretangot RH/LH)
		<li>Teboil Voiteluaineet ja Nestekaasut
		<li>ELGA Hitsauslangat/puikot, Laikat yms
		<li>Muototeräkset (lisäksi Männänvarret, Pintakarkaistut, RST ja Alumiini)
		<li>Rengastyöt (K-A ja Traktorin renkaat)
		<li>Varastosta käytetyt, uudet, pinnoitetut kuorma-autonrenkaat + vanteet
		<li>Valotarvikkeet (12-24v)
		<li>Auranterät (tasa-, verkko-, kovametalli ja tappiterät)
		<li>Ketjut, Koukut, Vaijerit ja Liittimet
		<li>Huollot / Korjaukset / Varaosat RK
		<li>Mählers ja Drivex Sopimushuoltopiste / Myynti
		<li>Engcon korjaukset
		<li>CAT Kynsiholkit ja Istukat varastosta
		<li>Kulutuslevut / Huulilevyt
	</div>
	<div id="right-col">
		 <div class="side-block">
			<h3>Navigointi</h3>
			<ul id="side-nav">
				<li>
					<a href="#">Palvelut</a>
					<ul>
						<li><a href="#koneistus">Koneistus</a></li>
						<li><a href="#huolto">Huolto</a></li>
						<li><a href="#varaosat">Varaosat</a>
						<li><a href="#muut-palvelut">Muut palvelut</a></li>
					</ul>
				</li>
				<!--
				<li>
					<a href="#">Sivusto</a>
					<ul>
						<li><a href="#">Tietoa sivustosta</a></li>
						<li><a href="#">Käyttöehdot</a></li>
						<li><a href="#">Sivukartta</a></li>
					</ul>
				</li>
				-->
			</ul>
		</div>

		<div class="sidebar-showcase">
			<h3>Kuvia myymälästä</h3>
			<img src="<?=ROOT_DIR?>/img/showcase/Hydr3.jpg" alt="" class="img-bordered">
			<img src="<?=ROOT_DIR?>/img/showcase/Laakerit.jpg" alt="" class="img-bordered">
			<img src="<?=ROOT_DIR?>/img/showcase/Pultit.jpg" alt="" class="img-bordered">
			<p class="clear"></p>
		</div>

	</div>
</div>