<ul class="top-nav">
<li><a href="<?=ROOT_DIR?>/dashboard"<?php if ($this->active == 'index') : ?> class="active"<?php endif;?>>Hallintapaneeli</a></li>
<li><a href="<?=ROOT_DIR?>/dashboard/products"<?php if ($this->active == 'products') : ?> class="active"<?php endif;?>>Tuotteet</a></li>
<li><a href="<?=ROOT_DIR?>/dashboard/gallery"<?php if ($this->active == 'gallery') : ?> class="active"<?php endif;?>>Galleria</a></li>
<li><a href="<?=ROOT_DIR?>/dashboard/settings"<?php if ($this->active == 'settings') : ?> class="active"<?php endif;?>>Asetukset</a></li>
</ul>

<span id="log_out"><a href="<?=ROOT_DIR?>/dashboard/login">Kirjaudu ulos</a></span>