<ul class="top-nav">
<li><a href="/ArtomiSys2/"<?php if ($this->active == 'index') : ?> class="active"<?php endif;?>>Etusivu</a></li>
<li><a href="/ArtomiSys2/services"<?php if ($this->active == 'services') : ?> class="active"<?php endif;?>>Palvelumme</a></li>
<li><a href="/ArtomiSys2/products"<?php if ($this->active == 'products') : ?> class="active"<?php endif;?>>Tuotteet</a></li>
<li><a href="/ArtomiSys2/gallery"<?php if ($this->active == 'gallery') : ?> class="active"<?php endif;?>>Galleria</a></li>
<li><a href="/ArtomiSys2/contact"<?php if ($this->active == 'contact') : ?> class="active"<?php endif;?>>Ota yhteyttä</a></li>
</ul>