<!--
	DASHBOARD
-->

<!DOCTYPE html>
<html>
	<head>
		<title><?=$this->title;?></title>
		<meta charset="utf-8"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		
		<meta name="description" content="Kuljetus & konepaja Artomi Oy on Vihannissa toimiva kuljetusalan ja koneistuksen ammattilainen." />
		<meta name="keywords" content="Kuljetus Artomi Oy, metallityöt, koneistukset, Vihanti, kuorma-autokuljetukset, kuljetukset, konepaja" />
		
		<link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
		
		<?php
		if (isset($this->css)) {
			echo '<link rel="stylesheet" href="'. $this->css .'"/>';
		}
		?>
	</head>
	<body>
		<div id="header">
		<?=!empty($this->snippets['header']) ? $this->snippets['header'] : '';?>
		</div>
		<div class="wrapper">
		<?=$this->output;?>
		</div>
	</body>
</html>