<!--
	DASHBOARD
-->

<!DOCTYPE html>
<html>
	<head>
		<title><?=$this->title;?></title>
		<meta charset="utf-8"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		
		<meta name="description" content="Kuljetus & konepaja Artomi Oy on Vihannissa toimiva kuljetusalan ja koneistuksen ammattilainen." />
		<meta name="keywords" content="Kuljetus Artomi Oy, metallityöt, koneistukset, Vihanti, kuorma-autokuljetukset, kuljetukset, konepaja" />
		
		<link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
		
		<?php
		if (isset($this->css)) {
			echo '<link rel="stylesheet" href="'. $this->css .'"/>';
		}
		?>
	</head>
	<body>
		<?=!empty($this->snippets['header']) ? $this->snippets['header'] : '';?>
		
		<?php if(!empty($_SESSION['notification'])): ?>
		
		<!-- Show notification -->

		<div id="notification" class="notification notification-<?=$_SESSION['notification']['type']?>">
			<?=$_SESSION['notification']['message']?>
			<?php $this->clearNotification()?>
		</div>

		<?php endif ?>
		
		<?=$this->output;?>

		<?=!empty($this->snippets['footer']) ? $this->snippets['footer'] : '';?>

		<!-- Javascripts -->
		<script type="text/javascript" src="<?=ROOT_DIR?>/js/main.js"></script>
	</body>
</html>